apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-health-customizations
  namespace: openshift-gitops
  labels:
    group: applications
spec:
  project: cp4i-operators
  source:
    path: 'argocd/healthcustomization'
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
