apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: sample-qm-1
spec:
  license:
    accept: true
    license: L-RJON-CD3JKX
    metric: VirtualProcessorCore
    use: PATCHED_BY_KUSTOMIZE
  queueManager:
    route:
      enabled: true
    name: SAMPLEQM1
    availability:
      type: SingleInstance
    storage:
      queueManager:
        type: PATCHED_BY_KUSTOMIZE
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    mqsc:
    - configMap:
        name: sample-qm1-cm
        items:
        - tls.mqsc
  version: 9.3.1.1-r1
  web:
    enabled: true