apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: wellknown-cert-qm
spec:
  queueManager:
    storage:
      queueManager:
        class: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
      recoveryLogs:
        class: ibmc-block-gold