apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zone:
    name: my-zone # (optional) name of the zone of the host
  cluster:
    name: replace-me # replace with the name of your Kubernetes cluster
  agent:
    key: replace-me # replace with your Instana agent key
    endpointHost: ingress-red-saas.instana.io # the monitoring ingress endpoint
    endpointPort: "443" # the monitoring ingress endpoint port, wrapped in quotes
    env:
      INSTANA_AGENT_TAGS: example
    configuration_yaml: |
      # You can leave this empty, or use this to configure your instana agent.
      # See https://docs.instana.io/setup_and_manage/host_agent/on/kubernetes/