apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: instana-monitoring
spec:
  type: serverconf
  description: Configuration for enabling instana monitoring
  data: UmVzb3VyY2VNYW5hZ2VyczoNCiAgT3BlblRlbGVtZXRyeU1hbmFnZXI6DQogICAgb3BlblRlbGVtZXRyeUVuYWJsZWQ6IHRydWUgIyBFbmFibGUgb3IgZGlzYWJsZSBPcGVuVGVsZW1ldHJ5IHRyYWNpbmcuIEF2YWlsYWJsZSBvbiBMaW51eC94ODYtNjQuDQogICAgZXhwb3J0ZXJPdGxwR3JwY0VuZHBvaW50OiAiaW5zdGFuYS1hZ2VudC5pbnN0YW5hLWFnZW50LnN2Yzo0MzE3IiAjIFRoZSBHUlBDIGVuZHBvaW50IHRvIHdoaWNoIHRoZSBPcGVuVGVsZW1ldHJ5IHNwYW4gZGF0YSBpcyBzZW50LiBGb3IgZXhhbXBsZSwgJ3RlbGVtZXRyeWFnZW50Lmhvc3QuY29tOjQzMTcnLg==
