kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_ZRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate