apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operators
spec:
  generators:
  - list:
      elements:
        - name: apiconnect
          namespace: openshift-operators
        - name: appconnect
          namespace: openshift-operators
        - name: common
          namespace: openshift-operators
        - name: eventstreams
          namespace: openshift-operators
        - name: mq
          namespace: openshift-operators
        - name: platformnavigator
          namespace: openshift-operators
        - name: aspera
          namespace: openshift-operators
  template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
    spec:
      project: 'cp4i-operators'
      source:
        repoURL: https://github.com/Nordic-MVP-GitOps-Repos/hypersonic-lightweight-cp4i.git
        targetRevision: 'HEAD'
        path: 'components/{{name}}/operator'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true