apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: recovery_group
          role: Recovery
          tls:
            key:
              items:
                - tls.key
                - tls.crt
            secretName: NHACRR_recovery_ext
        remotes: 
          - addresses:  
            - "<livegrouphost:port>"
            name: live_group
        trust: 
          - secret:   
              items:
              - tls.crt       
            secretName: NHACRR_live_ext