apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: recovery_group
          role: Recovery
          tls:
            key:
              secretName: mq-external-tls-secret
              items:
                - tls.key
                - tls.crt
        remotes: 
          - addresses:  
            - example.com:443
            name: live_group
        trust: 
          - secret:
              secretName: mq-external-tls-secret   
              items:
              - tls.crt       
            