apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: light-insecure
  namespace: cp4i
spec:
  security:
    internalTls: NONE
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: false
    monitoring: false
  strimziOverrides:
    kafka:
      config:
        inter.broker.protocol.version: '3.3'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: light-insecure-metrics-config
        type: jmxPrometheusExporter
      storage:
        type: ephemeral
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
      replicas: 1
    zookeeper:
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: light-insecure-metrics-config
        type: jmxPrometheusExporter
      storage:
        type: ephemeral
      replicas: 1
  adminUI: {}
  restProducer: {}
  apicurioRegistry: {}
  adminApi: {}
  collector: {}
  version: latest
