apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:

- rook-crds.yaml
- rook-operator.yaml
- rook-argo-role.yaml
- privileged-scc-rb.yaml

patchesStrategicMerge:
- storage-class.yaml