apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pwx-claim
  namespace: rook-nfs
spec:
  storageClassName: platform-navigator-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi