kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-argo-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - apiextensions.k8s.io
      - apps
      - nfs.rook.io
      - ""
    resources:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rook-argo-rb
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-argo-role