apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:    
        local:
            name: live_group
            role: Live
            tls:
                key:
                    items:
                      - tls.key
                      - tls.crt
                    secretName: NHACRR_live_ext
        remotes: 
            addresses:  
                  - "<recoverygrouphost:port>"
            name: recovery_group
            trust: 
                  - secret:   
                      items:
                        - tls.crt       
                      secretName: NHACRR_recovery_ext
              