apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: native-ha-qm
spec:
  queueManager:
    availability:
      nativeHAGroups:
        local:
          name: no-east
          tls:
            key:
              secretName: default-cert-copy
              items:
                - tls.key
                - tls.crt
        remotes: 
          - addresses:  
            - native-ha-qm-crr-ibm-mq-nhacrr-cp4i.apps.mqpoc.norwaywest.aroapp.io:443
            name: no-west
            trust: 
              - secret:
                  secretName: default-cert-copy   
                  items:
                  - ca.crt       
                
