apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands
spec:
  generators:
     - matrix:
        generators:
          - list:
              elements:
                - name: mq
                  namespace: cp4i
                  sync-wave: "300"
                - name: reloader
                  namespace: cp4i
                  sync-wave: "200"
          - list:
              elements:
                - region: us-east
                - region: us-west      
  template:
    metadata:
      name: '{{region}}-{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: cp4i-operands
      source:
        path: 'envs/azure/{{region}}/{{name}}/'
      destination:
        server: '{{clusterUrl}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
