apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands-frankfurt
spec:
  generators:
  - list:
      elements:
        - name: mq
          namespace: cp4i
          sync-wave: "300"
        - name: reloader
          namespace: cp4i
          sync-wave: "200"
  template:
    metadata:
      name: 'frankfurt-{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: cp4i-operands
      source:
        path: 'envs/odf/frankfurt/{{name}}/'
      destination:
        server: https://api.67c1cda6bf028633dde83ab0.eu1.techzone.ibm.com:6443
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true