apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands-madrid
spec:
  generators:
  - list:
      elements:
        - name: mq
          namespace: cp4i
          sync-wave: "300"
        - name: reloader
          namespace: cp4i
          sync-wave: "200"
  template:
    metadata:
      name: 'madrid-{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: cp4i-operands
      source:
        path: 'envs/odf/madrid/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true