apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: wellknown-cert-qm
spec:
  queueManager:
    storage:
      queueManager:
        class: managed-premium
      persistedData:
        class: managed-premium
      recoveryLogs:
        class: managed-premium