apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-appconnect
spec:
  channel: "v7.0"
  name: ibm-appconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace