apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common
  namespace: openshift-gitops
  labels:
    group: applications
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/common/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true