apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-frankfurt
  namespace: openshift-gitops
  labels:
    group: applications
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: cp4i
    server: https://api.67c1cda6bf028633dde83ab0.eu1.techzone.ibm.com:6443
  project: default
  source:
    path: ./components/common/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
