apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-offices-ci
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ibmoffices
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./envs/azure/non-prod/ci
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/ibm-offices-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
