apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - cp4i-argo-role.yaml
  - cp4i-argo-rb.yaml

  - common.yaml

  - operators/operator-project.yaml
  - operators/all-operators.yaml
 
  - operands/operand-project.yaml
  - operands/all-operands.yaml
 
 # - apps/ibm-offices.yaml
 # - apps/ace-hello-world.yaml

patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: group=applications
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/Nordic-MVP-GitOps-Repos/hypersonic-lightweight-cp4i.git
    - op: add
      path: /spec/source/targetRevision
      value: HEAD