apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
spec:
  channel: "v2.2"
  name: ibm-appconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace