apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-hello-world-ci
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ace-hello-world
    server: https://kubernetes.default.svc
  project: ace-hello-world
  source:
    path: ./envs/azure/non-prod/ci
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-hello-world-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ace-hello-world
    server: https://kubernetes.default.svc
  project: ace-hello-world
  source:
    path: ./envs/azure/non-prod/app
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/ace-hello-world-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: IntegrationServer
    name: ace-hello-world-is
    namespace: ace-hello-world
    jsonPointers:
    - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ace-hello-world
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'

