apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-offices-ci
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ibmoffices
    server: https://kubernetes.default.svc
  project: ibm-offices
  source:
    path: ./envs/ibm-classic/non-prod/ci
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/ibm-offices-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-offices-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: ibmoffices
    server: https://kubernetes.default.svc
  project: ibm-offices
  source:
    path: ./envs/ibm-classic/non-prod/app
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/ibm-offices-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ibm-offices
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'

