apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - sample-qm1/sample-qm1.yaml
  # - sample-qm1/sample-qm1-cm.yaml

  - sample-qm2/sample-qm2.yaml
  - sample-qm2/sample-qm2-configmap.yaml
  
  - tls/issuer.yaml
  - tls/selfsigned-nativeha-cert.yaml
  - tls/haqmchl-route.yaml
  - tls/mq-server-tls.yaml