apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: platform-navigator
spec:
  license:
    accept: true
    license: L-RJON-CJR2RX
  mqDashboard: true
  replicas: 1
  storage:
    class: PATCHED_BY_KUSTOMIZE
  version: 2022.4.1
  # See: https://www.ibm.com/docs/en/cloud-paks/cp-integration/2022.4?topic=certificates-using-custom-hostnames-platform-ui
  tls:
    secretName: "pn-lec-cert-secret"
    serverCertificate: tls.crt
    caCertificate: tls.crt
    key: tls.key
  uiHostname: "lhscp4i.ceibm.com"