apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../components/platform-navigator/variants/cloudprovider/azure

resources:
- ../../../components/platform-navigator/base